/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author amirhsn
 */
public class Book_Views extends javax.swing.JFrame {
    private Connection connection;
    private int userID;
    private DefaultComboBoxModel<String> modelComboBox;
    private MainMenu_Views mainMenuViews;
    
    /**
     * Creates new form Book_Views
     */
    public Book_Views(Connection dbConnection, int userID) {
        this.connection = dbConnection;
        this.userID = userID;
        this.modelComboBox = getNoKamar();
        mainMenuViews = new MainMenu_Views(connection, userID);
        initComponents();
    }
    
    private DefaultComboBoxModel<String> getNoKamar() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        
        try {
            String query = "SELECT no_kamar FROM kamar_tersedia WHERE status = 'available'";
            PreparedStatement statement = connection.prepareStatement(query);

            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                model.addElement(String.valueOf(resultSet.getInt("no_kamar")));
            }
            resultSet.close();
            statement.close();
//            connection.close();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Load data gagal, cobalah beberapa saat lagi" + e.getMessage());
        }
        
        return model;
    }
    
    private String generateRandomTarif(String tarif){
        // Hapus 3 digit terakhir
        String modifiedString = tarif.substring(0, tarif.length() - 3);
        
        // Menghasilkan angka unik random dengan tiga digit
        Random random = new Random();
        int randomDigits = random.nextInt(999);
        
        // Menggabungkan angka unik random dengan string yang telah diubah
        String result = modifiedString + String.format("%03d", randomDigits);
        
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>(modelComboBox);
        jlNominal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbSelesaiBook = new javax.swing.JButton();
        jbKembaliFromBook = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtfNIMBook = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("ASRAMA TELKOM UNIVERSITY");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("BOOKING KAMAR FORM");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Tipe Kamar");

        jlNominal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jlNominal.setForeground(new java.awt.Color(255, 153, 153));
        jlNominal.setText("NOMINAL AKAN KELUAR SAAT ANDA KLIK REGISTRASI");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setText("Silahkan lakukan transfer sesuai nominal  ke rekening BCA 987654321 a.n Admin Asrama");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setText("Digit terakhir haruslah sama karena itu nomor unik yang menandakan pendaftaran anda.");

        jbSelesaiBook.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jbSelesaiBook.setText("REGISTRASI");
        jbSelesaiBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelesaiBookActionPerformed(evt);
            }
        });

        jbKembaliFromBook.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jbKembaliFromBook.setText("KEMBALI");
        jbKembaliFromBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliFromBookActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("NIM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNIMBook, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbKembaliFromBook, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jbSelesaiBook, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfNIMBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSelesaiBook, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbKembaliFromBook, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbKembaliFromBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliFromBookActionPerformed
        // Navigate to MainMenu
        mainMenuViews.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbKembaliFromBookActionPerformed

    private void jbSelesaiBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelesaiBookActionPerformed
        // Sanity check
        if (jtfNIMBook.getText().equals("") || jtfNIMBook.getText().length() < 6){
            JOptionPane.showMessageDialog(null, "Harap isi NIM dan pastikan lebih dari 5 karakter");
        }
        try{
            int nimInt = Integer.parseInt(jtfNIMBook.getText());
            // Check dulu sudah ada di DB atau belum
            String query = "UPDATE kamar_tersedia SET booked_by = ? WHERE no_kamar = ?;";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, String.valueOf(userID)); // set nilai booked_by (pakai interpolasi)
            statement.setString(2, jComboBox1.getSelectedItem().toString()); // set nilai no_kamar (pakai interpolasi)

            int rowsUpdated = statement.executeUpdate();
    
            if (rowsUpdated > 0) {
                query = "SELECT tarif FROM kamar_tersedia WHERE no_kamar = ?";
                statement = connection.prepareStatement(query);
                statement.setString(1, jComboBox1.getSelectedItem().toString()); // set nilai no_kamar (pakai interpolasi)
                ResultSet resultSet = statement.executeQuery();
                if (resultSet.next()) {
                    String newTarif = generateRandomTarif(resultSet.getString("tarif"));
                    JOptionPane.showMessageDialog(null, "Registrasi berhasil, transfer ke rekening dengan nominal berikut: "+newTarif);
                    mainMenuViews.setVisible(true);
                    dispose();
                } else {}
            } else {
                JOptionPane.showMessageDialog(null, "Terdapat kesalahan pada sistem, coba lagi nanti.");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Harap masukkan format angka di NIM"+e.getMessage());
        }
    }//GEN-LAST:event_jbSelesaiBookActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Book_Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Book_Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Book_Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Book_Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Book_Views().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbKembaliFromBook;
    private javax.swing.JButton jbSelesaiBook;
    private javax.swing.JLabel jlNominal;
    private javax.swing.JTextField jtfNIMBook;
    // End of variables declaration//GEN-END:variables
}
