/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amirhsn
 */
public class MainMenu_Views extends javax.swing.JFrame {
    private Connection connection;
    private DefaultTableModel modelTableOne, modelTableTwo;
    private int userID;

    /**
     * Creates new form MainMenu_Views
     */
    public MainMenu_Views(Connection dbConnection, int userID) {
        this.connection = dbConnection;
        this.userID = userID;
        this.modelTableOne = fillKamarTersediaTable();
        this.modelTableTwo = fillKamarDiprosesTable();
        initComponents();
    }

    private DefaultTableModel fillKamarTersediaTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. Kamar");
        model.addColumn("Kapasitas");
        model.addColumn("Fasilitas");
        model.addColumn("Tarif");
        
        try {
            String query = "SELECT * FROM kamar_tersedia WHERE status = 'available'";
            PreparedStatement statement = connection.prepareStatement(query);

            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                int no_kamar = resultSet.getInt("no_kamar");
                String kapasitas = resultSet.getString("kapasitas");
                String fasilitas = resultSet.getString("fasilitas");
                String tarif = resultSet.getString("tarif");
    
                model.addRow(new Object[]{no_kamar, kapasitas, fasilitas, tarif});
            }
            resultSet.close();
            statement.close();
//            connection.close();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Load data gagal, cobalah beberapa saat lagi");
        }
        
        return model; 
    }
    
    private DefaultTableModel fillKamarDiprosesTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. Kamar");
        model.addColumn("Kapasitas");
        model.addColumn("Fasilitas");
        model.addColumn("Tarif");
        model.addColumn("Status");
        
        try {
            String query = "SELECT * FROM kamar_tersedia WHERE booked_by = ?";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, String.valueOf(userID));

            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                System.out.println(resultSet.getInt("no_kamar"));
                int no_kamar = resultSet.getInt("no_kamar");
                String kapasitas = resultSet.getString("kapasitas");
                String fasilitas = resultSet.getString("fasilitas");
                String tarif = resultSet.getString("tarif");
                String status = resultSet.getString("status");
    
                model.addRow(new Object[]{no_kamar, kapasitas, fasilitas, tarif, status});
            }
            resultSet.close();
            statement.close();
//            connection.close();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Load data yang diproses gagal, cobalah beberapa saat lagi" + e.getMessage());
        }
        
        return model; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtKamarTersedia = new javax.swing.JTable(modelTableOne);
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtKamarProses = new javax.swing.JTable(modelTableTwo);
        jLabel4 = new javax.swing.JLabel();
        jbToBookKamar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jbKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("ASRAMA TELKOM UNIVERSITY");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("DAFTAR KAMAR YANG TERSEDIA");

        jScrollPane1.setViewportView(jtKamarTersedia);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("DAFTAR KAMAR ANDA YANG SEDANG DI PROSES");

        jScrollPane2.setViewportView(jtKamarProses);

        jLabel4.setText("Catatan: Pendaftaran hanya untuk kamar asrama yang akan ditempati di tahun ajaran berikutnya selama satu tahun.");

        jbToBookKamar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbToBookKamar.setText("BOOK");
        jbToBookKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbToBookKamarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setText("BOOK KAMAR? ");

        jbKeluar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbKeluar.setText("KELUAR");
        jbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26)
                                .addComponent(jbToBookKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                                .addComponent(jbKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jbToBookKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jLabel4)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbToBookKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbToBookKamarActionPerformed
        // Check apakah id sudah booking sebelumnya
        try {
            String query = "SELECT * FROM kamar_tersedia WHERE booked_by = ?";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, String.valueOf(userID)); // set nilai booked_by (pakai interpolasi)

            ResultSet resultSet = statement.executeQuery();

            // Check kalau query balikin minimal 1 baris
            if (resultSet.next()) {
                JOptionPane.showMessageDialog(null, "Maaf, kamu sudah book kamar asrama sebelumnya");
            } else {
                // Navigate ke menu booking
                Book_Views bookViews = new Book_Views(connection, userID);
                bookViews.setVisible(true);
                dispose();
            }

//        // Tutup koneksi db
//        connection.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Maaf, terjadi kegagalan dalam sistem, harap coba kembali beberapa saat"+e.getMessage());
        }
    }//GEN-LAST:event_jbToBookKamarActionPerformed

    private void jbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKeluarActionPerformed
        // Navigate to login form
        Login_Views loginViews = new Login_Views(connection);
        loginViews.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbKeluarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainMenu_Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainMenu_Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainMenu_Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainMenu_Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenu_Views().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbKeluar;
    private javax.swing.JButton jbToBookKamar;
    private javax.swing.JTable jtKamarProses;
    private javax.swing.JTable jtKamarTersedia;
    // End of variables declaration//GEN-END:variables
}
